### ISSUE TITLE
아이템 18. 상속보다는 컴포지션을 사용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#1]

**Comment by ssibongee** [comment]
1. 상속은 캡슐화를 깨뜨린다. 즉, 상위 클래스와 하위 클래스가 높은 의존성을 가지고 상위 클래스의 변경에 따라 하위 클래스가 제대로 동작하지 않을 수 있다.
2. 결국 상속은 상위 클래스를 자유롭게 변경하기 어렵다는 것과 상속을 잘못 사용할 경우 의도하지 않은 동작을 수행할 수 있다는 문제가 존재한다.
3. 때문에 상속보다는 기능을 재사용하고 싶은 클래스가 있다면 새로운 클래스를 생성하고 필드를 통해 기존의 클래스의 인스턴스를 참조하게하는 컴포지션을 사용하는 것을 권장한다.
4. 컴포지션은 상속에서 발생하는 상위 클래스와의 높은 의존성으로 인한 문제와 상속을 잘모사 사용하여 의도치 않은 동작이 수행될 수 있는 문제를 해결해준다.

**Comment by vincentj2** [comment]
- 클래스가 다른 클래스를 확장하는 구현 상속의 경우 상위 클래스는 릴리스마다 내부 구현이 달라질 수 있으며, 그 여파로 하위 클래스가 오동작 할 수 있다.
- 기존 클래스를 확장하는 대신, 새로운 클래스를 만들고 private 필드로 기존 클래스의 인턴스를 참조하게 한다.
- 상속은 반드시 하위 클래스가 상위 클래스의 '진짜' 하위 타입인 상황에서만 쓰여야 하며, 클래스 B가 클래스 A와 is-a 관계일 때만 클래스 A를 상속해야 한다.
- 기존 클래스가 새로운 클래스의 구성요소로 쓰이는 설계 방식을 컴포지션이라 한다.
