### ISSUE TITLE
아이템 54. null이 아닌, 빈 컬렉션이나 배열을 반환하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#10]

**Comment by vincentj2** [comment]
1. `null`을 반환한다면, 클라이언트는 `null` 상황을 처리하는 코드를 추가로 작성해야 한다.
2. `null`을 반환하지 않는 방법을 사용할 때는 수정 전과 후의 성능을 측정하여 성능이 개선되는지 확인하자.

**Comment by ssibongee** [comment]
1. `null` 을 반환한다는 것은 잠재적으로 NullPointerException을 가지게 된다 때문에 `null` 상황을 처리하는 방어 코드가 필요하며 이로 인하여 코드가 더 복잡해지게 된다.
2. `null` 대신에 빈 컬렉션이나 빈 배열을 반환하고 만약 최적화가 필요한 경우 미리 생성된 배열이나 컬렉션을 반환하자.
3. 위의 경우에는 최적화에 해당하므로 꼭 필요한 경우만 사용하고 실제로 테스트를 통해 성능이 개선되었는지 확인하자.
