### ISSUE TITLE
아이템 72. 표준 예외를 사용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#11]

**Comment by vincentj2** [comment]
1. 예외 클래스 수가 적을수록 메모리 사용량도 줄고 클래스를 적재하는 시간도 적게 걸린다.
2. `Exception`, `RuntimeException`,`Throwable`,`Error`는 직접 재사용하지 말자. 다른 예외들의 상위 클래스이므로 안정적으로 테스트할 수 없기 때문이다.
3. 인수 값이 무엇이었든 어차피 실패했을거라면 `IllegalStateExceptiopn`을, 그렇지 않으면 `IllegalArgumentException`을 던지자.

**Comment by ssibongee** [comment]
1. 표준 예외는 많은 개발자들에게 이미 익숙해진 규약을 그대로 따르기 때문에 읽기 쉽고 이를 재사용하기 때문에 메모리 사용량 및 클래스 로드 시간에도 장점을 가진다.
2. `Exception`, `RuntimeException` `Throwable`, `Error` 클래스는 여러 성격의 예외들을 포괄하는 클래스이기 때문에 안정적으로 테스트 할 수 없으며 추상 클래스라고 생각하고 이를 확장해서 더 정확한 정보를 전달할 수 있는 예외를 정의하는 것이 좋다.
