### ISSUE TITLE
아이템 85. 자바 직렬화의 대안을 찾으라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#12]

**Comment by ssibongee** [comment]
> 참고
- https://techblog.woowahan.com/2551/
- https://techblog.woowahan.com/2550/

**Comment by ssibongee** [comment]
1. 직렬화의 근본적인 문제는 공격 범위가 넓어 방어하기 힘들다는 점인데 특히 신뢰할 수 없는 스트림을 역직렬화 하는 경우에 원격 코드 실행, 서비스 거부 공격 등에 쉽게 노출될 수 있다.
2. 때문에 자바 직렬화 보다는 이러한 위험을 회피하면서 훨씬 간단한 `JSON` 이나 프로토콜 버퍼 등의 대안을 사용하는 것이 좋다.
3. 만약 어쩔 수 없이 직렬화를 지원해야 한다면 역직렬화 필터링이나 역직렬화로 인한 보안 취약점을 회피할 수 있도록 신경써서 작성해야한다.

**Comment by vincentj2** [comment]
1. 직렬화 위험을 회피하는 가장 좋은 방법은 아무것도 역직렬화하지 않는 것이다. 새로운 시스템에서 자바 직렬화를 써야 할 이유는 전혀 없다.
2. 레거시로 인해 자바 직렬화를 배제할 수 없을 때의 차선책은 신뢰할 수 없는 데이터는 절대 역직렬화하지 않는 것이다.
3. 직렬화가 꼭 필요한 경우에는 객체 역직렬화 필터링을 사용하되, 모든 공격을 막을 수 없음을 기억해야 한다.
