### ISSUE TITLE
아이템 86. Serializable을 구현할지는 신중히 결정하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#13]

**Comment by vincentj2** [comment]
1. `Serializable`을 구현한 클래스는 릴리즈 후에 수정이 어렵고 버그와 보안에 취약하며 새로운 버전을 릴리즈할 때 테스트 요소가 많아진다.
2. 상속 목적으로 설계된 클래스와 대부분의 인터페이스는 `Serializable`을 구현하면 안된다. 클래스를 확장하거나 인터페이스를 구현하는 대상에게 위험성을 그대로 전이하는 것이다.
3. 내부 클래스는 직렬화를 구현하면 안된다. 내부 클래스는 바깥 인스턴스의 참조와 유효 범위에 속한 지역변수를 저장하기 위한 필드가 필요하다.
4. 이 필드들은 컴파일러가 자동으로 추가하는데, 익명 클래스와 지역 클래스의 네이밍 규칙이 자바 명세에 없는 것처럼 이 필드들도 어떻게 추가되는지 알 수가 없다. 단, 정적 멤버 클래스는 예외다.

**Comment by vincentj2** [comment]
참고 
- https://madplay.github.io/post/java-serialization-advanced

**Comment by ssibongee** [comment]
1. 직렬화는 `Serializable` 을 구현하기만 하면 쉽게 적용가능하지만 직렬화를 적용한 클래스는 릴리즈 이후에 수정이 어렵고 수정을 위해서는 여러 버전 호환성을 고려해야한다.
2. 특히 직렬화된 모든 클래스는 `serialVersionUID`를 부여받는데 이를 명시하지 않을 경우에도 런타임에 자동으로 생성해서 넣어주게 된다. 때문에 클래스 이름, 멤버, 메서드 등이 변경되면 `serialVersionUID`도 변경되기 때문에 역직렬화시 문제가 발생할 수 있다.
3. 직렬화는 버그와 보안상의 취약점으로 작용할 수 있는데 특히 역직렬화는 생성자를 거치지 않고 객체를 생성하는 것과 동일하기 때문에 불변식과 허가되지 않은 접근에 쉽게 노출되게 된다.
4. `static`이 아닌 내부 클래스는 외부의 인스턴스의 참조와 유효 범위 안의 지역변수 값들을 저장하기 위해서 컴파일러가 생성한 필드들이 자동으로 추가되기 때문에 직렬화를 구현하면 안된다.
