### ISSUE TITLE
아이템 15. 클래스와 멤버의 접근 권한을 최소화하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#14]

**Comment by vincentj2** [comment]
1. 정보 은닉의 장점으로는 시스템 개발 속도를 높이고 관리 비용을 낮추며 소프트웨어 재사용성을 높이고 큰 시스템을 제작하는 난이도를 낮춰주는 것이 있다.
2. 모든 클래스와 멤버의 접근성을 가능한 한 좁혀야 한다. 꼭 필요한 것만 골라 최소한의 `public API` 를 설계하자.
3. `public` 클래스는 상수용 `public static final`  필드 외에는 어떠한 `public` 필드도 가져서는 안된다.
4. 자바 9에서는 모듈 시스템이라는 개념이 도입되어 두 가지 암묵적 접근 수준이 추가되었다.

**Comment by ssibongee** [comment]
1. 잘 설계된 컴포넌트는 클래스의 내부 데이터와 내부 구현 정보를 외부 컴포넌트로부터 완벽하게 숨기며 API를 통해서만 외부 컴포넌트와 소통한다. 즉, 캡슐화가 잘되어있다.
2. 캡슐화는 시스템의 개발 속도를 높이며, 관리 비용을 낮춰준다. 뿐만 아니라 소프트웨어 재사용성과 각각의 모듈 사이의 의존성을 낮춤으로써 성능과 테스트에도 여러가지 장점을 제공한다.
3. 접근성은 가능한 낮게 할당하는 것을 권장하며 상수용 필드 이외에는 어떠한 필드도 `public` 접근 제한자를 가져서는 안된다.
