### ISSUE TITLE
아이템 24. 멤버 클래스는 되도록 static으로 만들라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#15]

**Comment by vincentj2** [comment]
1. 메서드 밖에서도 사용해야 하거나 메서드 안에 정의하기엔 너무 길다면 멤버 클래스도 만든다.
2. 멤버 클래스의 인스턴스 각각이 바깥 인스턴스를 참조한다면 비정적 멤버 클래스로, 그렇지 않다면 정적 멤버 클래스도 만들자.
3. 중첩 클래스가 한 메서드 안에서만 사용되며 그 인스턴스를 생성하는 지점이 단 한곳이고 해당 타입으로 쓰기에 적합한 클래스나 인터페이스가 이미 존재한다면 익명 클래스로 만들고 그렇지 않으면 지역 클래스로 만들자.
4. 익명 클래스는 자바가 람다를 지원하면서 주 쓰임이 정적 팩터리 메서드를 구현할 때로 변경되었다.

**Comment by ssibongee** [comment]
1. `static` 키워드가 붙은 클래스는 중첩 클래스에만 존재할 수 있으며 이러한 클래스를 정적 멤버 클래스라고 한다.
2. 비정적 멤버 클래스는 외부 클래스 인스턴스에 대한 숨은 참조를 가지게되기 때문에 이러한 참조로 인하여 외부 클래스 객체가 GC되지 않아 최악의 경우 Memory Leak이 발생할 수 있다.
