### ISSUE TITLE
아이템 20. 추상 클래스보다는 인터페이스를 우선하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#16]

**Comment by vincentj2** [comment]
1. 추상 클래스가 정의한 타입을 구현하는 클래스는 반드시 추상 클래스의 하위 클래스가 되어야 한다.
2. 추상 클래스는 기존 클래스에 덧씌울 수 없기 때문에 믹스인을 정의할 수 없다.
3. `equals`와 `hashcode` 같은 `object`의 메서드는 디폴트 메서드로 제공하면 안된다.
4. 다중 구현용 타입으로는 인터페이스가 가장 적합하며 복잡한 인터페이스의 경우 골격 구현을 함께 제공하는 방법을 고려하라.

**Comment by ssibongee** [comment]
1. 추상 클래스는 다중 상속이 불가능할 뿐만 아니라 기존 클래스에 덧씌울 수 없기 때문에 믹스인을 정의할 수 없다.
2. 때문에 진짜 `is-a` 관계가 아니라면 인터페이스를 사용하는 것을 권장한다.
3. 인터페이스는 `Object`의 메서드인 `equals()` , `hashCode()` 와 같은 메서드를 디폴트 메서드로 정의하면 안된다.
4. 인터페이스는 인스턴스 필드를 가질 수 없고 `public`이 아닌 정적 멤버도 가질 수 없기 때문에 이러한 제약사항들을 개선하기 위해 인터페이스와 골격 클래스라고 불리는 추상 클래스를 같이 사용한다.
