### ISSUE TITLE
아이템 26. RawType은 사용하지 말라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#17]

**Comment by vincentj2** [comment]
1. 제네릭 타입을 하나 정의하면 그에 딸린 raw type도 함께 정의된다.
2. raw type이란 제네릭 타입에서 타입 매개변수를 전혀 사용하지 않을 때를 말한다.
3. 매개변수로 List를 받는 메서드에 `List<String>`을 넘길 수 있지만, `List<Object>`를 받는 메서드에는 넘길 수 없는데 이것은 제네릭의 하위 타입 규칙 때문이다.
4. 와일드카드 타입은 안전하고, raw type은 안전하지 않다.
5. raw type을 사용하면 런타임에 예외가 일어날 수 있으니 사용하면 안된다.

**Comment by ssibongee** [comment]
1. RawType은 제네릭 타입 지정없이 제네릭 클래스 타입을 사용하는 것을 의미한다.
2. Raw Type은 하위 호환성을 위해 존재하는 것이지 제네릭이 제공하는 타입 안정성을 깨트리기 때문에 사용하면 안된다.
3. 제네릭은 특정 파라미터 타입만 허용하기 때문에 모든 파라미터 타입을 허용하고 싶다면 비한정적 와일드카드를 사용해야 한다.
4. 비한정적 와일드카드를 사용하는 제네릭 컬렉션은 `null` 이외에 다른 값을 넣을 수 없다.
