### ISSUE TITLE
아이템 30. 이왕이면 제네릭 메서드로 만들라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#18]

**Comment by vincentj2** [comment]
1. 제네릭은 런타임에 타입 정복 소거되므로 하나의 객체를 어떤 타입으로든 매개변수화 할 수 있다.
2. 타입 한정인 `<E extends Comparable<E>>`는 모든 타입 E는 잣신과 비교할 수 있다 라는 의미이다.
3. 제네릭 타입과 마찬가지로, 클라이언트에서 입력 매개변수와 반환값을 명시적으로 형변환 해야하는 메서드보다 제너릭 메서드가 더 안전하며 사용하기 쉽다.

**Comment by ssibongee** [comment]
1. 클라이언트에서 입력 매개변수와 반환값을 명시적으로 형변환 해야하는 메서드 보다는 제네릭 메서드가 더 안전하고 사용하기 쉽다.
2. 때문에 형변환이 필요한 기존의 메서드는 제네릭하게 만드는 것이 좋다.
