### ISSUE TITLE
아이템 11. equals를 재정의하려거든 hashCode도 재정의하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#19]

**Comment by vincentj2** [comment]
1. `equals` 비교에 사용되는 정보가 변경되지 않았다면, 애플리케이션이 실해되는 동안 그 객체의 `hashcode` 메서드는 몇 번을 호출해도 일관되게 항상 같은 값을 반환해야 한다.
2. `equals(Object)`가 두 객체를 같다고 판단했다면, 두 객체의 `hashCode`는 똑같은 값을 반환해야한다.
3. 클래스가 불변이고 해시코드를 계산하는 비용이 크다면, 매번 새로 계산하기 보다는 캐싱하는 방식을 고려해야 한다.
4. 성능을 높이기 위해 해시코드를 계산할때 핵심 필드를 생략한다면 오히려 해시 품질 이 나빠져 헤시테이블의 성능을 떨어뜨릴 수 있다.

**Comment by ssibongee** [comment]
1. `HashSet` , `HashMap` 과 같은 컬렉션 타입은 객체의 `hashCode()` 를 비교한 이후에 객체를 `equals()`로 비교하기 때문에 객체의 내용이 같더라도 해시 코드가 다르면 다른 객체로 판단하게 된다.
2. 개발자가 생성한 클래스는 어떻게 사용될지 모르기 때문에 `equals()`와 `hashCode()`를 재정의 하지 않은 상태로 `HashMap`과 `HashSet`에서 사용하는 경우 제대로 동작하지 않을 수 있다.
3. 클래스가 불변이고 `hashCode()`를 계산하는 비용이 크다면 매번 새로 계산하는 것보다는 캐싱하는 방식을 고려해야한다.
4. 성능을 위해 해시 값을 계산할 때 핵심 필드를 생략할 경우 속도는 개선될지 몰라도 해시 품질이 나빠져 오히려 성능을 심각하게 저하시킬 수 있다.
