### ISSUE TITLE
아이템 79. 과도한 동기화는 피하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#2]

**Comment by ssibongee** [comment]
1. 과도한 동기화는 성능을 떨어뜨리고, 교착상태에 빠뜨리며, 심지어 예측 불가능한 동작을 수행한다. 때문에 동기화 블록 내에서 제어 불가능한 코드를 호출해서는 안된다.
2. 동기화 블록 내에서 제어 불가능한 코드는 동기화 블록 밖으로 옮기고 동기화 블록에서는 가능한 일을 적게 유지하는 것이 좋다.
3. 과도한 동기화가 초래하는 비용은 락을 획득하는데 발생하는 비용이 아니라 경쟁하느라 낭비하는 시간이다.
4. 즉, 병렬로 실행할 기회를 잃고 모든 코어가 메모리를 일관되게 보기 위한 지연 시간이 비용으로써 작용할 뿐만 아니라 가상머신의 코드 최적화도 제한한다.
5. 때문에 CopyOnWriteArrayList 등의 동기화가 필요없는 자료구조를 고려하자.

**Comment by ssibongee** [comment]
### 💡 Fail-Fast Iterators
- iterator 의 remove() 메서드 이외의 코드로 기존의 컬렉션이 수정되면 Fail-Fast Iterators라는 예외가 발생한다.
- 컬레션은 내부 카운터를 유지하기 때문에 컬렉션에서 항목을 추가 또는 제거할 때마다 카운터가 증감된다.
- 반복을 수행하면서 next() 를 호출해서 카운터의 현재값이 초기값과 일치하는지 여부를 비교해서 불일치할 경우 전체 작업을 중단시키는 ConcurrentModificationException 이 발생한다.
- ArrayList, HashMap 등과 같은 컬렉션 클래스에 대한 기본 반복자는 Fail-Fast 이다.
컬레션은 내부 카운터를 유지하기 때문에 컬렉션에서 항목을 추가 또는 제거할 때마다 카운터가 증감된다.
반복을 수행하면서 next() 를 호출해서 카운터의 현재값이 초기값과 일치하는지 여부를 비교해서 불일치할 경우 전체 작업을 중단시키는 ConcurrentModificationException 이 발생한다.
ArrayList, HashMap 등과 같은 컬렉션 클래스에 대한 기본 반복자는 Fail-Fast 이다.

**Comment by vincentj2** [comment]
1. 응답 불가(교착상태) 와 안전 실패(데이터 훼손)를 피하려면 동기화 메서드나 동기화 블록 안에서는 제어를 절대로 클라이언트에 양도하면 안 된다.
2. 자바의 재진입 가능 락은 객체 지향 멀티스레드 프로그램을 쉽게 구현할 수 있도록 하지만, 교착상태가 될 상황을 데이터 훼손으로 변모시킬 수도 있다.
3. 동기화 영역 바깥에서 호출되는 외계인 메서드* 를 열린 호출(open call)이라 하며, open call은 실패 방지 효과 외에도 동시성 효율을 크게 개선해준다.

* 외계인 메서드(alien method) : 동기화된 영역을 포함한 클래스 관점에서 클라이언트가 넘겨준 동작방법을 모르며 통제할 수 없는 메서드
