### ISSUE TITLE
아이템 25. 톱레벨 클래스는 한 파일에 하나만 담으라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#20]

**Comment by vincentj2** [comment]
1. 컴파일러에 어느 소스 파일을 먼저 건네느냐에 따라 동작이 달라진다.
2. 다른 클래스에 따린 부타적인 클래스라면 정적 멤버 크래스로 만드는 쪽이 읽기 좋고, `private`으로 선언하면 접근 범위도 최소로 관리할 수 있다.
3. 소스 파일 하나에는 반드시 톱레벨 클래스를 하나만 담자.

**Comment by ssibongee** [comment]
1. 하나의 파일에 여러 톱레벨 클래스가 정의되어있는 경우 컴파일 순서에 따라서 어떤 클래스가 먼저 참조될지 변할 수 있기 때문에 실행 결과가 달라질 수 있다.
2. 때문에 일반적으로 하나의 파일에 하나의 클래스를 관리하는 것을 권장한다.
3. 만약 하나의 클래스 파일에 여러 톱레벨 클래스를 정의하고 싶다면 정적 멤버 클래스를 사용하는 방법을 고려하자.
