### ISSUE TITLE
아이템 31. 한정적 와일드카드를 사용해 API 유연성을 높이라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#21]

**Comment by vincentj2** [comment]
1. 매개변수화 타입은 `invariant`이다.
2. `List<String>`은 `List<Object>`가 하는 일을 제대로 수행하지 못하니 리스코프 치환 원칙에 어긋나고 하위 타입이 될 수 없다.
3. 유연성을 극대화하려면 원소의 생산자나 소비자용 입력 매개변수에 와일드카드 타입을 사용하라.
4. `PECS` : producer-extends, consumer-super 원칙을 기억하자.
5. 매서드 선언에 타입 매개변수가 한 번만 나오면 와일드카드로 대체하자.
6. `Comparable`과 `Comparator`는 모두 소비자라는 것을 기억하자

**Comment by ssibongee** [comment]
1. 매개변수화 타입은 불공변 즉, 상속관계에 상관없이 자기 타입만 허용이 가능하다.
2. 때문에 `List<String>`는 `List<Object>`가 하는 일을 제대로 수행할 수 없기 때문에 리스코프 치환원칙에 어긋나며 하위 타입이 될 수 없다.
3. 이러한 상황에 대처하기 위해서 한정적 와일드카드 타입을 사용할 수 있다. List<? extends Object>`
4. 와일드카드 타입을 적용하기 위한 원칙으로 PECS라는 것이 있으며 `T`의 `producer`라면 `extends`를 `consumer`라면 `super`를 사용하라는 것을 의미한다.
5. 리턴 타입에서는 `extends` , `super` 등의 한정적 와일드카드를 사용하며 클라이언트 코드에서도 이를 강제해야하기 때문에 사용하면 안된다.
