### ISSUE TITLE
아이템 42. 익명 클래스보다는 람다를 사용하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#22]

**Comment by vincentj2** [comment]
1. 자바 8 이후에 추상 메서드 하나짜리 인터페이스는 함수형 인터페이스라고 불리며 인스턴스를 람다식을 사용해 만들 수 있게 되었다.
2.  타입을 명시해야 코드가 더 명확할 때만 제외하고는, 람다의 모든 매개변수 타입은 생략하자
3. 람다는 이름이 없고 문서화도 못한다. 따라서 코드 자체로 동작이 명확히 설명되지 않거나 코드 줄 수가 많아지면 람다를 쓰지 말아야 한다.
4.  열거 타입 생성자에 넘겨지는 인수들의 타입도 컴파일타입에 추론된다. 따라서 열거 타입 생성자 안의 람다는 열거 타입의 인스턴스 멤버에 접근할 수 없다. (인스턴스는 런타임에 만들어지기 때문)

**Comment by ssibongee** [comment]
1. 익명클래스는 컴파일 이후 별도의 클래스 파일을 생성할 뿐만 아니라 코드가 너무 길고 가독성이 떨어진다는 단점이 존재하기 때문에 람다식을 사용하는 것을 권장한다.
2. 람다식에서 반드시 컴파일러가 추론을 통해 매개변수의 타입을 결정하기 때문에 타입을 반드시 명시해야하는 경우를 제외하고는 이를 생략하는 것이좋다.
3. 람다식은 이름이 없으며 문서화도 불가능하기 때문에 코드 자체로 동작이 명확하게 설명되지 않거나 코드가 길어지는 경우에는 람다식을 사용하기 보다는 메서드 참조를 이용하는 것이 좋다.
4. 람다에서 `this` 키워드는 바깥의 인스턴스를 가리키고 익명 클래스에서의 `this`는 익명 클래스 자신을 가리키기 때문에 객체가 자신을 참조해야 한다면 익명 클래스를 사용해야한다.
