### ISSUE TITLE
아이템 46. 스트림에서는 부작용 없는 함수를 사용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#23]

**Comment by vincentj2** [comment]
1. 스트림 패러다임의 핵심은 계산을 일련의 변환으로 재구성하는 부분이다.
2. `forEach` 연산은 스트림 계산 결과를 보고할 때만 사용하고, 계산하는 데는 쓰지 말자.
3. 스트림뿐 아니라 스트림 관련 객체에 건네지는 모든 함수 객체가 부작용이 없어야 한다.
4. 스트림을 사용하기 위한 수집기 팩터리는 `toList`, `toSet`, `toMap`, `groupingBy`, `joining`이 있다.

**Comment by ssibongee** [comment]
1. 스트림 패러다임의 핵심은 계산을 일련의 변환으로 재구성하는 것으로 각 변환 단계는 이전 단계의 결과만 받아서 처리하는 순수함수이어야 한다.
2. 순수함수란 오직 입력만이 결과에 영향을 주며 다른 가변 상태를 참조하거나 변경하지 않는 함수를 의미하며 순수함수를 사용할 경우 스트림 연산에 건내지는 함수 객체는 모두 사이드 이펙트로 부터 자유로울 수 있다.
3. `forEach`으로 외부 상태를 변경하여 사이드 이펙트를 발생시키거나 `reduce` 연산으로 모든 것을 처리하는 식의 방법은 스트림을 잘못 이해하고 사용하고 있는 것이다.
