### ISSUE TITLE
아이템 48. 스트림 병렬화는 주의해서 적용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#24]

**Comment by vincentj2** [comment]
1. 동시성 프로그래밍을 할 때는 안전성과 응답 가능 상태를 유지하기 위해 애써야 하는데, 병렬 스트림 파이프라인 프로그래밍에서도 다를바 없다.
2. 스트림을 잘못 병렬화하면 성능이 나빠질 뿐만 아니라 겨과 자체가 잘못되거나 예상 못한 동작이 발생할 수 있다.
3. 스트림 병렬화는 오직 성능 최적화 수단임을 기억해야 한다.
4. 계산도 정확하고 성능도 좋아졌음이 확실해졌을 때, 오직 그럴 때만 병렬화 버전 코드를 운영코드에 반영하라.

**Comment by ssibongee** [comment]
1. 병렬 스트림을 제대로 알고 사용하지 않을 경우 오히려 성능 저하로 이어질 수 있다. 대표적으로 데이터 소스가 `Stream.iterate` 이거나 중간 연산으로 `limit`를 사용하는 경우가 이에 해당한다.
2. 때문에 스트림 파이프라인을 마구잡이로 병렬화하면 안되고 스트림의 소스가 `ArrayList` , `HashMap` , `HashSet` , `ConcurrentHashMap` 의 인스턴스이거나 배열의 `int` 및 `long` 범위 일 때 병렬화의 효과가 가장 좋다.
3. 스트림 병렬화는 성능 최적화를 위한 수단이며 확신과 테스트 없이 스트림 파이프라인 병렬화를 적용하는 경우 이 효과를 제대로 얻을 수 없을 뿐만 아니라 오히려 성능 저하로 이어지거나 예상치 못한 결과가 나타날 수 있다.
