### ISSUE TITLE
아이템 67. 최적화는 신중히 하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#25]

**Comment by vincentj2** [comment]
1. 좋은 프로그램은 정보 은닉 원칙을 따르므로 개별 구성요소의 내부를 독립적으로 설계할 수 있다.
2. 시스템을 설계할 때 API, 네트워크 프로토콜, 영구 저장용 데이터 포맷을 설계할 때는 성능을 염두에 두어야 한다.
3. 시스템 구현 후 성능이 좋지 않다면 프로파일러를 사용해 문제의 원인이 되는 지점을 찾아 최적화를 수행하라.

**Comment by ssibongee** [comment]
1. 성능 때문에 견고한 구조를 희생하려하지 말고, 빠른 프로그램 보다는 좋은 프로그램을 작성하기 위해 노력하자 잘 설계된 프로그램은 그 자체가 최적화 할 수 있는 길을 안내해 줄 것이다.
2. 성능을 제한하는 설계를 피해야하며 API를 설계할 때는 성능에 주는 영향을 고려해야한다 이러한 설계 요소들은 완성 후에는 변경이 어렵거나 불가능할 수 있으며 시스템의 성능을 심각하게 제한할 수 있다.
3. 꼭 최적화가 필요한 경우에만 프로파일링 도구를 이용해서 최적화가 필요한 지점을 찾아 이를 수행하고 최적화 전후로 반드시 성능 측정을 통해서 이를 확인해야한다.
