### ISSUE TITLE
아이템 69. 예외는 진짜 예외 상황에만 사용하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#26]

**Comment by vincentj2** [comment]
1. 예외는 오직 예외 상황에서만 써야 한다. 절대로 일상적인 제어 흐름용으로 쓰여선 안된다.
2. 특정 상태에서만 호출 할 수 있는 `상태 의존적` 메서드를 제공하는 클래스는 `상태 검사` 메서드도 함께 제공해야 한다.
3. `상태 검사` 메서드 대신 `optional` 혹은 `null` 같은 특수한 값을 반환하는 방법이 있다.

**Comment by ssibongee** [comment]
1. 예외는 오직 예외 상황에서만 사용해야하며 절대로 일상적인 제어 흐름용으로 사용해서는 안된다.
2. 잘못된 예외의 사용은 코드의 가독성을 떨어트릴 뿐만 아니라 오히려 성능을 저하시키고 예외상황을 정상적인 상황으로 오해하고 넘어가 결과적으로 제대로 동작하지 않는 프로그램을 만들 가능성이 존재한다.
2. 잘 설계된 API는 클라이언트가 정상적인 제어 흐름에서 예외를 사용할 일을 만들지 않는다.
