### ISSUE TITLE
아이템 83. 지연 초기화는 신중히 사용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#27]

**Comment by vincentj2** [comment]
1. `지연초기화`는 필드의 초기화 시점을 그 값이 처음 필요할 떄까지 늦추는 기법이다.
2. 주로 최적화 요도로 쓰이지만, 클래스와 인스턴스 초기화때 발생하는 순환 문제를 해결하는 효과도 있다.
3. 대부분의 상황에서는 일반적인 초기화가 지연 초기화보다 낫다.
4. 인스턴스 필드에는 `이중검사 관용구`를, 정적 필즈에는 `지연 초기화 홀더 클래스 관용구`를 사용하자.
5. 반복해 초기화 해도 괜찮은 인스턴스 필드에는 `단일검사 관용구`를 고려하자.

**Comment by ssibongee** [comment]
1. 지연 초기화는 최적화와 마찬가지로 필요할 때 까지 하지 않는 것이 가장 좋다.
2. 지연 초기화는 클래스 또는 인스턴스 생성시 초기화 비용을 줄어들지만 지연 초기화하는 필드에 접근하는 비용이 증가하게 되기 때문에 각 필드를 얼마나 빈번하게 호출하는지에 따라서 오히려 성능이 저하될 수 있다.
3. 지연 초기화가 초기화의 순환성을 깨뜨리는 경우에는 `synchronized`를 사용하고 성능을 위해서라면 `Lazy Holder` 방식을 사용하거나 `Double Check` 방식을 사용할 수  있다.
