### ISSUE TITLE
아이템 3. private 생성자나 열거 타입으로 싱글턴임을 보증하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#28]

**Comment by vincentj2** [comment]
1. 싱글턴이란 인스턴스를 오직 하나만 생성할 수 있는 클래스를 말한다.
2. 싱글턴을 만드는 방법 모두 생성자는  `private`으로 감춰두고, 유일한 인스턴스에 접근할 수 있는 수단으로 `public static` 멤버를 하나 만들어둔다.
3. `public static` 멤버가 `final` 필드인 방식과 정적 팩터리 메서드를 `public static` 멤버로 제공하는 방식이 있다.
4. 마지막 방법은 원소가 하나인 열거 타입을 선언하는 것이다.
5. 대부분 상황에서는 원소가 하나뿐인 열거 타입이 싱글턴을 만드는 가장 좋은 방법이다.

**Comment by ssibongee** [comment]
1. 무상태 객체나 설계상 유일해야하는 시스템 컴포넌트는 싱글턴으로 설계하여 오직 하나의 인스턴스만 생성하도록 보장할 수 있다.
2. 싱글턴을 만드는 방법에는 `public static final` 필드로 제공하는 방법과 정적 펙터리 메서드를 제공하는 방법, 단일 원소를 가지는 열거 타입으로 정의하는 방법이 존재한다.
3. 클래스를 이용해서 싱글턴을 정의하는 경우 역직렬화 할 때 매번 새로운 인스턴스가 만들어진다는 문제점이 존재하기 때문에 `readResolve()` 메서드를 재정의하여 이를 방지해야한다.
4. 반면에 열거 타입을 이용하면 이러한 문제 뿐만 아니라 복잡한 직렬화 및 리플랙션 공격에도 새로운 인스턴스가 생성되는 것을 막아주기 때문에 이를 이용하는 것이 가장 바람직하다.
