### ISSUE TITLE
아이템 6. 불필요한 객체 생성을 피하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#29]

**Comment by vincentj2** [comment]
1. 생성자 대신 정적 팩터리 메서드를 제공하는 불변 클래스에서는 불필요한 객체 생성을 피할 수 있다.
2. 불필요한 객체를 만들어내는 예로는 `auto boxing`이 있다.
3. `auto boxing`은 기본 타입과 그에 대응하는 박싱된 기본 타입의 구분을 흐려주지만, 완전히 없애주는 것은 아니다.
4. 박싱된 기본 타입보다는 기본 타입을 사용하고, 의도치 않은  `auto boxing`이 숨어들지 않도록 주의하자.

**Comment by ssibongee** [comment]
1. 불필요한 객체 생성은 성능 저하로 이어질 수 있다.
2. 문자열을 `new` 키워드로 생성하는 것은 매번 실행할 때마다 같은 문자열을 반복해서 생성하게되는데 JVM 내부에 스트링 풀을 이용해서 리터럴 스트링을 저장하고 재활용하기 때문에 `new` 대신 리터럴 스트링으로 생성하는 것이 좋다.
3. 정규표현식 인스턴스 `Pattern`은 한번 사용하고 버려져서 가비지 컬렉션의 대상이될 뿐만 아니라 인스턴스 생성 비용이 높다. 때문에 이를 캐싱해두고 재사용하는 것이 성능 뿐만 아니라 코드의 의미도 정확해진다.
4. 오토박싱은 불필요한 인스턴스를 생성하는 대표적인 케이스이기 때문에 박싱된 타입보다는 기본 타입을 사용하고 의도치 않은 오토박싱이 발생하지 않도록 주의해야한다.
5. 새로운 객체가 필요한 상황이라면 기존의 객체를 재활용해서는 안된다. 특히 방어적 복사의 경우 객체의 재사용하지 않는 객체는 단순히 코드의 형태와 성능에만 영향을 끼치지만 객체 재활용으로 인한 피해가 언제 발생할지 모르는 버그와 보안 취약점으로 작용할 수 있다.
