### ISSUE TITLE
아이템 80. Thread 보다는 Executor, Task, Stream을 애용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#3]

**Comment by ssibongee** [comment]
1. 직접 작업 큐를 만들거나 쓰레드를 직접 다루는 일은 일반적으로 삼가야한다. 
2. 이는 불필요한 실패나 응답 불가 될 가능성을 없애는 코드를 추가해야할 뿐만 아니라 작업의 단위와 수행 매커니즘 역할을 모두 수행하게 된다.
3. `Executor` 는 작업의 단위와 실행 매커니즘을 분리해줄 뿐만 아니라 여러가지 편의 기능들을 제공한다.
4. 또한 병렬 스트림은 내부적으로 `ForkJoinPool`을 이용해서 Job Stealing을 통해 CPU를 최대한 활용하면서 높은 처리량과 낮은 지연시간을 달성하게 도와준다.

**Comment by ssibongee** [comment]
### 💡 Runnable 과 Callable
이 둘은 비슷하지만 `Callable`은 값을 반환하고 임의의 예외를 던질 수 있다는 가장 큰 차이점이 존재한다.

**Comment by vincentj2** [comment]
1. 큐를 둘 이상의 스레드가 처리하게 하고 싶다면 간단히 다른 정적 팩터리를 이용하여 다른 종류의 스레드 풀을 생성하면 된다.
2. 작고 가벼운 프로그램의 경우 `CachedTreadPool`을, 무거운 프로덕션 서버에서는 스레드 개수를 고정한 `FixedThreadPool` 이나 완전히 통제할 수 있는 `ThreadPoolExecutor`를 사용하는 것이 좋다.
3. 스레드를 직접 다루면 `Thread`가 작업 단위와 수행 메커니즘 역할을 모두 수행하게 된다.
