### ISSUE TITLE
아이템 13. clone 재정의는 주의해서 진행하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#30]

**Comment by vincentj2** [comment]
1. `Cloneable` 인터페이스는 `Object`의 `protected` 메서드인 `clone`의 동작 방식을 결정한다.
2. 재정의한 메서드의 반환 타입은 상위 클래스의 메서드가 반환하는 타입의 하위 타입일 수 있다.
3. `clone` 메서드는 생성자와 같은 효과를 내며, 원본 객체에 아무런 영향을 주지 않고 복제된 객체의 불변식을 보장해야한다.
4. `Cloneable`을 구현한 스레드 안전 클래스를 작성할 때는 `clone` 메서드 역시 적절히 동기화해줘야 한다.
5. `Cloneable` 인터페이스를 구현하지 않고 `복사 생성자`와 `복사 팩터리`라는 더 나은 객체 복사 방식을 사용할 수 있다.

**Comment by ssibongee** [comment]
1. Cloneable 인터페이스는 `clone()`의 동작 방식을 결정하며 이를 구현한 클래스에서 `clone()`을 호출하면 해당 객체의 필드를 하나하나 복사한 객체를 반환하며 그렇지 않은 객체에서 이를 호출하면 CloneNotSupportedException을 반환하게 된다.
2. Cloneable이 제대로 동작한다는 기대를 만족하려면 해당 클래스를 구현한 클래스와 모든 상위 클래스가 Cloneable의 프로토콜을 지켜야하는데 이는 깨지기 쉽고 위험하고 상당히 모순적이며 생성자를 호출하지 안혹도 새로운 객체를 생성할 수 있게 된다.
3. 때문에 일반적으로 Cloneable을 구현해서 재정의하는 것보다는 복사 생성자 또는 복사 펙터리 메서드를 사용하는 것이 좋다.
