### ISSUE TITLE
아이템 12. toString을 항상 재정의하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#31]

**Comment by vincentj2** [comment]
1. `toString`의 일반 규약에 따르면 '간결하면서 사람이 읽기 쉬운 형태의 우익한 정보'를 반환해야한다.
2. `toString`의 규약은 '모든 하위 클래스에서 이 메서드를 재정의하라'고 한다.
3. `toString`은 객체가 가진 주요 정보를 모두 반환하는것이 좋다.

**Comment by ssibongee** [comment]
1. 기본적으로 `toString()` 메서드는 클래스 이름과 16진수로 표시한 해시코드 값을 반환하는데 이 것으로는 어떠한 유의미한 정보도 얻을 수 없기 때문에 이를 재정의해서 간결하면서 읽기 쉬운 형태의 유익한 정보를 반환해야한다.
2. `toString()`을 잘 구현한 코드는 디버깅하기 쉬우며 `toString()`을 구현할 때 되도록이면 가지고있는 주요 정보들을 모두 반환하는 것이 좋다.
