### ISSUE TITLE
아이템 62. 다른 타입이 적절하다면 문자열 사용을 피하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#32]

**Comment by vincentj2** [comment]
1. 문자열은 열거 타입을 대신하기에 적합하지 않다.
2. 문자열은 권한을 표현하기에 적합하지 않다.
3. 더 적합한 데이터 타입이 있거나 새로 작성할 수 있다면, 문자열을 사용하지 말자.

**Comment by ssibongee** [comment]
1. 문자열은 텍스트를 표현하도록 설계되었기 때문에 다른 값 타입을 대신하기에 적합하지 않다. 
2. 위와 같은 이유로 문자열은 열거 타입이나 혼합 타입을 대신하기에 적합하지 않으며 추가적으로 권한을 표현하기에도 적합하지 않다.
3. 결국 문자열을 잘못 사용하게되면 번거롭고, 덜 유연하며, 느리고, 오류 가능성이 크기 때문에 되도록이면 다른 적절한 타입이 존재할 경우 해당 타입을 사용하는 것이 좋다.
