### ISSUE TITLE
아이템 38. 확장할 수 있는 열거 타입이 필요하면 인터페이스를 사용하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#34]

**Comment by vincentj2** [comment]
1. 타입 안전 열거 패턴은 확장할 수 있으나 열거 타입은 그럴 수 없다.
2. 인터페이스를 이용해 확장 가능한 열거 타입을 흉내 내는 방식의 문제는 열거 타입끼리 구현을 상속할 수 없다는 것이다.
3. 열거 타입 자체는 확장할 수 없지만, 인터페이스와 그 인터페이스를 구현하는 기본 열거 타입을 함께 사용해 같은 효과를 낼 수 있다.

**Comment by ssibongee** [comment]
1. 열거 타입은 확장이 불가능하다. 즉, `extends`를 통해서 상속이 불가능하다는 의미이다.
2. 열거 타입을 확장하는 것은 좋지 않지만 연산 코드와 같은 특정 케이스에는 열거 타입을 확장할 필요성이 존재하고 이 경우 인터페이스를 통해 문제를 해결할 수 있다.
3. 인터페이스를 정의하고 열거 타입을 인터페이스의 표준 구현체 역할을 하도록 구현하면 열거 타입을 확장하는 것과 같은 효과를 얻을 수 있다.

**Comment by ssibongee** [comment]
`Operation` 인터페이스를 확장하면서 제네릭 인터페이스로 만들고 이를 열거 타입이 확장되게 하여 다양한 연산 타입을 만족하도록 코드를 작성해보려고 시도하였는데 다음의 이유로 불가능하다.
1. 열거 타입을 타입 파라미터를 이용해서 제네릭 타입으로 만드는 것은 불가능하다.
2. 인터페이스가 제네릭 타입이더라도 열거 타입 내부에서 타입 파라미터를 사용할 수 없기 때문에 컴파일시 타입이 정해져야 한다.
https://stackoverflow.com/questions/4290878/why-shouldnt-java-enum-literals-be-able-to-have-generic-type-parameters
