### ISSUE TITLE
아이템 43. 람다보다는 메서드 참조를 사용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#35]

**Comment by vincentj2** [comment]
1. 람다로 할 수 없는 일이라면 메서드 참조로도 할 수 없다.
2. 메서드 참조 유형은 정적 메서드를 가리키는 메서드 참조, 한정적 인스턴스 메서드 참조, 비한정적 인스턴스 메서드 참조, 클래스 생성자를 가리키는 메서드 참조와 배열 생성자를 가리키는 메서드 참조가 있다.
3. 람다로는 불가능하나 메서드 참조로는 가능한 유일한 예는 제네릭 함수 타입 구현이다.

**Comment by ssibongee** [comment]
1. 메서드 참조는 기능을 잘 들어내는 이름을 지어줄수 있고 설명을 문서로 남길 수도 있다. 때문에 람다식이 길고 복잡해진다면 메서드 참조를 그렇지 안다면 람다식을 사용하는 것이 좋다.
2. 람다식으로 할 수 있는 일은 대부분 메서드 참조로 할 수 있고 그 대우도 대부분의 경우에 만족하지만 제네릭 메서드의 경우에는 람다식으로 표현할 수 없다.
