### ISSUE TITLE
아이템 44. 표준 함수형 인터페이스를 사용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#36]

**Comment by vincentj2** [comment]
1. 필요한 용도에 맞는 게 있다면, 직접 구현하지 말고 표준 함수형 인터페이스를 활용하라.
2. 기본 함수형 인터페이스에 박싱된 기본 타입을 넣어 사용하지 말자.
3.  직접 만든 함수형 인터페이스에는 항상 `@FunctionalInterface` 를 사용하라.


- `Comparator`의 특성
  - 자주 쓰이며, 이름 자체가 용도를 명확히 설명해준다.
  - 반드시 따라야하는 규약이 있다.
  - 유용한 디폴트 메서드를 제공할 수 있다.

- `@FuntionalInterface`를 사용하는 이유
   - 해당 클래스의 코드나 설명 문서를 읽을 이에게 람다용으로 설계된 것을 알려준다.
   - 인터페이스가 추상 메서드를 오직 하나만 가지고 있어야 컴파일되게 해준다.
   - 유지보수 과정에서 누군가 실수로 메서드를 추가하지 못하게 막아준다.

**Comment by ssibongee** [comment]
1. 가능한 표준 함수형 인터페이스를 사용하는 것이 불필요한 클래스를 생성하지 않아도 될 뿐만 아니라 다른 코드와의 상호운용성도 크게 좋아지게 만든다. 
2. 때문에 표준 인터페이스에 정의된 함수형 인터페이스 중에서 용도에 맞는 것이 없는 경우에만 직접 작성하는 것이 좋다.
2. 함수형 인터페이스에 박싱된 기본 타입을 넣어서 사용하는 것은 오토 박싱으로 인한 성능 저하를 가져오기 때문에 이를 사용하지 말자.
3. `@FunctionalInterface` 어노테이션은 해당 인터페이스가 함수형 인터페이스임을 명시적으로 드러내줄 뿐만 아니라 추상 메서드가 오직 한개만 존재하지 않을 경우 컴파일 예외를 발생시키기 때문에 개발자가 실수할 가능성을 줄여준다. 
4. 그렇기 때문에 직접 만든 함수형 인터페이스에는 `@FunctionalInterface` 어노테이션을 사용하는 것을 권장한다.
