### ISSUE TITLE
아이템 16. public 클래스에서는 public 필드가 아닌 접근자 메서드를 사용하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#37]

**Comment by ssibongee** [comment]
1. `public` 클래스의 멤버를 `public` 접근 제한자를 통해 외부로 노출할 경우 캡슐화가 깨지게 된다. 
2. 때문에 `public` 클래스의 모든 필드는 `private`을 사용해서 외부로 부터의 직접적인 접근을 막고 `public` 접근자 메서드를 통해서만 접근가능하게 해야한다.
3. `package-private`, `private` 중첩 클래스의 경우 데이터 필드를 노출한다고 하더라도 내부에서만 사용하는 클래스이기 때문에 문제가 발생하지 않는다.

**Comment by vincentj2** [comment]
1. `public` 클래스의 경우 패키지 바깥에서 접근할 수 있는 접근자를 제공함으로써 클래스 내부 표현 방식을 언제든 바꿀수 있는 유연성을 얻을 수 있다.
2. `package-private`, `private` 중첩 클래스의 경우 데이터 필드를 노출해도 문제가 없다.
3. `public` 클래스는 절대 가변 필드를 직접 노출해서는 안된다.
