### ISSUE TITLE
아이템 21. 인터페이스는 구현하는 쪽을 생각해 설계하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#38]

**Comment by vincentj2** [comment]
1. 디폴트 메서드는 컴파일에 성공하더라도 기존 구현체에 러타임 오류를 일으킬 수 있다.
2. 디폴트 메서드는 인터페이스로부터 메서드를 제거하거나 기존 메서드의 시그니처를 수정하는 용도가 아님을 명심해야 한다.
3. 인터페이스를 설계할 때는 세심한 주의를 기울여야 한다.

**Comment by ssibongee** [comment]
1. 디폴트 메서드는 기존의 구현 클래스와 반드시 매끄럽게 연동되리라 하는 보장이 없기 때문에 이를 사용할 때는 세심한 주의가 필요하다.
2. 디폴트 메서드는 메서드를 제거하거나 기존 메서드 시그니처를 수정하는 용도가 아니며 이러한 형태로 인터페이스를 변경하는 경우 기존 클라이언트를 망가뜨리게 된다.
3. 때문에 디폴트 메서드라는 도구가 생겼다고 하더라도 인터페이스 설계를 할 때는 세심한 주의가 필요하며 잘못된 인터페이스 설계는 이를 포함한 API에 심각한 버그를 가져올 수 있다.
