### ISSUE TITLE
아이템 40. @Override 애너테이션을 일관되게 사용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#39]

**Comment by vincentj2** [comment]
1. 상위 클래스의 메서드를 재정의하려는 모든 메서드에 `@Override` 애너테이션을 달자.
2. 구체 클래스에서 상위 클래스의 추상매서드를 재정의할 때는 굳이 `@Override`를 달지 않아도 된다.

**Comment by ssibongee** [comment]
1. `@Override` 어노테이션은 상위 클래스의 메서드를 잘못 재정의 하는 경우에 컴파일 타임에 오류를 알려준다.
2. 때문에 되도록이면 상위 클래스나 상위 인터페이스의 메서드를 재정의하는 모든 메서드에 `@Override`를 일관적으로 다는 것이 좋다.
