### ISSUE TITLE
아이템 51. 메서드 시그니처를 신중히 설계하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#4]

**Comment by vincentj2** [comment]
1. 메서드 이름은 항상 표준 명명 규칙을 따르며, 이해할 수 있고 일관될 수 있도록 신중하게 짓자.
2. 클래스나 인터페이스는 자신의 각 기능을 완벽히 수행하는 메서드를 제공해야하기 때문에 편의 메서드를 많이 만들지 말자.
3. 매개변수 목록은 4개 이하로 짧게 유지하기 위해 여러 매서드로 쪼개거나, 매개변수 여러 개를 묶어주는 도우미 클래스를 만들거나, 빌더 패턴을 사용하자.
5. 매개변수의 타입으로는 클래스보다는 인터페이스가 더 낫다.
6. boolean보다는 원소 2개짜리 열거 타입을 사용하여 가독성을 높히고 추후 선택지 추가가 용이하도록 한다.

**Comment by ssibongee** [comment]
1. 메서드의 이름은 표준 명명 규칙을 따라야하며 이해할 수 있고 일관되게 짓는 것이 최우선 목표이다.
2. 너무 많은 편의 메서드는 클래스를 유지보수하기 어렵게 만든다 때문에 꼭 필요한 메서드만 만드는 것이 좋다.
3. 메서드의 매개변수는 4개 이하로 유지하는 것이 좋으며 매개변수가 너무 길다면 여러 메서드로 쪼개거나, 매개변수를 묶어주는 클래스를 만들거나, 빌더 패턴을 사용하자.
4. 매개변수 타입으로는 특정 구현 클래스보다는 인터페이스를 사용하는 것이 좋다.
5. 참과 거짓이 딱 맞는 상황이라면 `boolean`을 사용하고 그게 아니라면 원소 2개 짜리 `enum` 타입을 사용하는 것이 가독성을 높이고 확장하기 쉽다.
