### ISSUE TITLE
아이템 22. 인터페이스는 타입을 정의하는 용도로만 사용하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#40]

**Comment by vincentj2** [comment]
1. 인터페이스는 자신을 구현한 클래스의 인스턴스를 참조할 수 있는 타입 역할을 한다.
2. 상수 인터페이스란 메서드 없이, 상수를 뜻하는 `static final` 필드로만 가득 찬 인터페이스를 의미한다.
3. `final`이 아닌 클래스가 상수 인터페이스를 구현한다면 모든 하위 클래스의 이름공간이 해당 인터페이스가 정의한 상수로 변경된다.

**Comment by ssibongee** [comment]
1. 인터페이스는 자신을 구현한 클래스의 인스턴스를 참조할 수 있는 타입 역할을 하며 인터페이스는 오직 이 용도로만 사용해야한다.
2. 상수 인터페이슨느 인터페이스를 잘못 활용한 대표적인 예시이다. 상수 인터페이스는 내부 구현을 클래스의 API로 노출할 뿐만 아니라 오히려 사용자에게 혼란을 주고 클라이언트 코드가 상수들에 종속되게 만든다.
3. 때문에 상수 인터페이스 대신 특정 클래스나 인터페이스 자체에 상수를 추가하거나 열거 타입을 활용할 수 있는 경우라면 이를 활용하는 것이 좋다.
