### ISSUE TITLE
아이템 58. 전통적인 for 문보다는 for-each 문을 사용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#41]

**Comment by vincentj2** [comment]
1. `for-each` 문은 반복자와 인덱스 변수를 사용하지 않으니 코드가 깔끔해지고 오류가 날 일이 없다.
2. `for-each` 문은 `파괴적인 필터링`, `변형`, `병렬 반복`의 3가지 경우에는 사용할 수 없다.
3. `for-each` 문은 컬렉션과 배열은 물론 `Iterable` 인터페이스를 구현한 객체라면 무엇이든 순회할 수 있다.

**Comment by ssibongee** [comment]
1. `for-each`는 반복자와 인덱스 변수를 사용하지 않으므로 코드가 깔끔해지고 오류가 발생할 일이 없을 뿐만 아니라 하나의 관용구로 컬렉션과 배열을 모두처리할 수 있어서 개발자가 어떤 컨테이너를 다루는지 신경쓰지 않아도 된다.
2. `for-each`는 다음과 같은 상황에서는 사용이 불가능하기 때문에 일반적인 `for`문을 고려해야한다.
  - 컬렉션을 순회하면서 선택된 원소를 제거하는 경우
  - 리스트나 배열을 순회하면서 원소의 값을 변경하거나 교체하는 경우 즉, 인덱스를 직접적으로 사용하는 경우
  - 여러 컬렉션을 병렬로 순회해야하는 경우, 이 경우도 인덱스를 직접적으로 제어해야하는 경우에 해당된다.
3. 위의 경우가 아니라면 `for-each`를 사용하는 것이 좋으며 `Iterable`인터페이스를 구현한 클래스라면 무엇이든 `for-each`를 사용할 수 있다.
