### ISSUE TITLE
 아이템 70. 복구할 수 있는 상황에는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#42]

**Comment by vincentj2** [comment]
1. 자바에서 문제 상황을 알리는 타입으로는 `checked exception`, `runtime exception`, `error`를 제공한다.
2. 호출하는 쪽에서 복구하리라 여겨지는 상황이라면  `checked exception`을 사용하라.
3. 프로그래밍 오류를 나타낼 때는 `runtime exception`을 사용하라.
4. 확실하지 않다면  `runtime exception`을 사용하라.

**Comment by ssibongee** [comment]
1. Java에서 문제 상황을 알리는 타입은 크게 `CheckedException`, `UncheckedException`, Error`로 구분할 수 있다.
2. 호출하는 쪽에서 복구가 가능한 상황잉라면 `CheckedException`을 사용해야한다.
3. 프로그래밍 오류를 나타낼 떄는 `UncheckedException`을 사용해야하며 대부분의 이런 프로그래밍 오류는 복구 불가능하거나 이를 판단하기가 애매모호한 경우가 많기 때문에 확신하기 어려운 상황이라면 `UncheckedException`을 선택하는 것이 좋다.
4. `Error`는 JVM이나 시스템 상의 문제로 인하여 더 이상 프로그램을 수행할 수 없을 때 사용되며 `Error`를 상속해서 하위 클래스를 만드는 것은 권장하지 않는다.
5. `Throwable`은 정상적인 검사 예외보다 나은 것이 없을 뿐만 아니라 사용자를 헷갈리게 만들 수 있기 때문에 절대 사용하지 않는 것을 권장한다.
