### ISSUE TITLE
아이템 61. 박싱된 기본 타입보다는 기본 타입을 사용하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#5]

**Comment by vincentj2** [comment]
1. 박싱된 기본 타입은 기본 타입과 달리 값과 식별성을 갖고 `null`을 가질 수 있다.
2. 박싱된 기본 타입에 `==` 연산자를 사용하게 되면 `객체 참조`의 식별성을 검사하게 되어 오류가 발생할 수 있다.
3. 박싱된 기본타입은 컬렉션의 원소, 키, 값으로 사용하며, 리플렉션을 통해 메서드를 호출할 때도 사용한다.

**Comment by ssibongee** [comment]
1. 박싱된 기본 타입은 식별성을 가지며 `null`을 가질 수 있기 때문에 `==` 연산을 수행한 결과 오류가 발생하거나 *NullPointerExceptin* 예외가 발생할 수 있다.
2. 또한 박싱된 기본타입은 불변 객체이기 때문에 잘못 사용하는 경우 불필요한 객체 생성으로 인한 성능저하가 발생할 수 있다.
3. 박싱된 기본 타입은 컬렉션의 원소나 키 값으로 사용하거나 리플랙션을 통해 메서드를 호출할 때에 사용한다.
4. 위의 경우가 아니라면 성능과 실수할 가능성을 줄이기 위해서 기본 타입을 사용하는 것이 좋다.
