### ISSUE TITLE
아이템 64. 객체는 인터페이스를 사용해 참조하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#6]

**Comment by vincentj2** [comment]
1. 적합한 인터페이스만 있다면 매개변수뿐 아니라 반환값, 변수, 필드를 전부 인터페이스 타입으로 선언한다.
2. `PriorityQueue`와 같은 인터페이스에는 없는 특별한 메서드를 제공하는 클래스의 경우 적합한 인터페이스가 없다면 클래스로 참조 해야한다. 
3. 적합한 인터페이스가 없다면 클래스의 계층구조 중 필요한 기능을 만족하는 가장 덜 구체적인(상위의) 클래스를 타입을 사용하자.

**Comment by ssibongee** [comment]
1. 객체를 표현하는 적합한 인터페이스가 있다면 매개변수 뿐만 아니라 반환값, 변수, 필드 전부 인터페이스로 선언하는 것이 좋다.
2. 구체적인 구현 클래스 대신에 인터페이스를 사용하는 것은 의존성을 낮추고 유연성을 높일 수 있다.
3. 만약 적합한 인터페이스가 없거나 인터페이스에 없는 특별한 메서드를 제공하는 클래스를 사용해야하는 경우에는 해당 클래스를 직접 참조해야한다.
