### ISSUE TITLE
아이템 63. 문자열 연결은 느리니 주의하라

### ISSUE THREAD

**Issue by ssibongee** [Today-I-Learn/lazy-effective-java#7]

**Comment by ssibongee** [comment]
1. 단순한 문자열 `+` 의 경우 컴파일러가 이를 내부적으로 `StringBuilder` 를 이용해서 최적화하기 때문에 괜찮지만 모든 경우에 최적화가 이루어지지는 않는다.
2. 반복문 내부에서는 `+` 연산이 자동으로 `StringBuilder` 로 변환되지 않아 불변 객체인 문자열 값을 양쪽다 복사해서 생성하는 비용이 발생하기 때문에 성능 저하가 일어나게 된다.
3. 때문에 복잡한 문자열 `+` 또는 반복문 안에서의 문자열 `+` 연산 대신에 성능을 위해서 `StringBuilder` 를 사용하는 것이 좋다.

**Comment by vincentj2** [comment]
1. 문자열 연결 연산자로 문자열 n개를 잇는 시간은 n <sup>2</sup> 에 비례한다. 
2. 문자열은 불변으로 두 문자열을 연결할 경우 양쪽의 내용을 모두 복사해야하므로 성능 저하가 발생할 수 있다.
3. 성능을 위해 `String` 대신 `StringBuilder`를 사용하자
