### ISSUE TITLE
아이템 17. 변경 가능성을 최소화하라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#8]

**Comment by vincentj2** [comment]
1. 클래스를 불변으로 만들기 위해서는 객체의 상태를 변경하는 메서드를 제공하지 않는다.
2. 클래스를 확장할 수  없도록 한다.
3. 모든 필드를 final로 선언한다.
4. 모든 필드를 private으로 선언한다.
5. 자신 외에는 내부의 가변 컴포넌트에 접근할 수 없도록 한다.
6. 불변으로 만들 수 없는 클래스의 경우 변경할 수 있는 부분을 최소한으로 줄여야 한다.

**Comment by ssibongee** [comment]
1. 불변 클래스는 상태 변화가 없어 안전하고 사용하기 쉬우며 오류가 생길 가능성이 적기 가능한 불변 클래스를 사용하는 것이 좋다.
2. 불변 클래스는 값이 다르면 매번 새로운 인스턴스를 생성해야한다는 단점이 존재하지만 이러한 단점을 개선하기 위해 내부에 가변 동반 클래스를 둘 수 있다.
3. 불변 클래스로 만들 수 없는 클래스가 있다면 가능한 변경할 수 있는 부분을 최소한으로 줄이는 것이 좋다.
