### ISSUE TITLE
아이템 76. 가능한 한 실패 원자적으로 만들라

### ISSUE THREAD

**Issue by vincentj2** [Today-I-Learn/lazy-effective-java#9]

**Comment by vincentj2** [comment]
1. 호출된 메서드가 실패하더라도 해당 객체는 메서드 호출 전 상태를 유지해야 하며 이러한 특성을 `failure-atomic` 이라 한다.
2. 매개변수의 유효성 검사를 작업 수행전 시행하여 `failure-atomic` 하게 만들 수 있다.
3. 객체의 임시 복사본에서 작업을 수행한 다음, 작업이 성공적으로 완료되면 원래 객체와 교체하는 방법으로 `failure-atomic`을 얻을 수 있다.

**Comment by ssibongee** [comment]
1. `failure-atomic` 이란 호출된 메서드가 실패하더라도 해당 객체는 메서드 호출 전의 상태를 유지하는 것을 의미한다.
2. `failure-atomic`을 만드는 방법은 불변 객체로 설계하거나 가변 객체의 경우 잠재적 예외 가능성을 검사하거나 또는 객체의 임시 복사본을 만들어 사용하는 방법이 존재한다.
3. `failure-atomic`은 권장되지만 두 쓰레드가 동시에 값을 변경해서 일관성을 꺠뜨리는 경우라던지 복구 블가능한 에러의 경우에는 달성이 불가능하거나 시도조차 할 필요가 없다.
